name: Destroy Express Backend

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  TF_VAR_node_env: prod
  TF_VAR_mongo_uri: ${{ secrets.MONGO_URI }}
  TF_VAR_rapid_api_key: ${{ secrets.RAPID_API_KEY }}
  TF_VAR_rapid_api_host: ${{ secrets.RAPID_API_HOST }}

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server/terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
